FROM node:10.10

WORKDIR /home/app

RUN apt-get update && apt-get install zsh -y

RUN npm i -g yarn

ADD package.json package.json
ADD yarn.lock yarn.lock

RUN yarn

ADD . .

CMD yarn start-plain-server
