version: '3.3'

services:
  traefik:
    image: traefik:v1.7.2-alpine
    # command: --api --docker --docker.domain=docker.localhost --logLevel=DEBUG
    command: --logLevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      # - /var/run/docker.sock:/var/run/docker.sock
      - ./proxies/traefik:/etc/traefik
      # - ./proxies/traefik/traefik.toml:/traefik.toml
  machine:
    image: katacoda/docker-http-server
    labels:
      - "traefik.backend=machine-echo"
      - "traefik.frontend.rule=PathPrefixStrip:/test"
  plain-http:
    build:
      context: .
      dockerfile: Dockerfile_plain_http
    volumes:
        - "./http2-plain:/home/app/http2-plain"  
    labels:
      - "traefik.backend=plain-http"   
